#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed=0
git remote update && git status -uno | grep -q 'Your branch is behind' && changed=1

if [ $changed = 1 ]; 
    then echo \"***WARNING***\n pull latest\";
    else yarn lint-staged
fi